from django.urls import path, re_path
from . import views

urlpatterns = [
	path('', views.cv_page, name='cv'),
	path('photo', views.cv_add_photo, name='cv_add_photo'),
	path('photo/create', views.new_area, name='new_area'),
	path('photo/add_item', views.add_item, name="add_item"),
	path('personal', views.cv_add_personal, name='cv_add_personal'),
	path('personal/create', views.new_area, name='new_area'),
	path('personal/add_item', views.add_item, name='add_item'),
	path('education', views.cv_add_education, name='cv_add_education'),
	path('education/create', views.new_area, name='new_area'),
	path('education/add_item', views.add_item, name='add_item'),
	path('experience', views.cv_add_experience, name="cv_add_experience"),
	path('experience/create', views.new_area, name="new_area"),
	path('experience/add_item', views.add_item, name="add_item"),
	path('skills', views.cv_add_skills, name='cv_add_skills'),
	path('skills/create', views.new_area, name="new_area"),
	path('skills/add_item', views.add_item, name='add_item'),
	path('personal/<int:pk>/', views.detail_personal, name='detail_personal'),
	path('education/<int:pk>/', views.detail_education, name="detail_education"),
	path('experience/<int:pk>/', views.detail_experience, name="detail_experience"),
	path('skills/<int:pk>/', views.detail_skills, name="detail_skills"),
	path('personal/<int:pk>/delete/', views.delete_personal, name="delete_personal"),
	#path('personal/<int:pk>/edit/', views.cv_add_personal, name="edit_personal"),
	path('education/<int:pk>/delete/', views.delete_education, name="delete_education"),
	#path('education/<int:pk>/edit/', views.edit_experience, name="edit_education"),
	path('experience/<int:pk>/delete/', views.delete_experience, name="delete_experience"),
	#path('experience/<int:pk>/edit/', views.edit_experience, name="edit_experience"),
	path('skills/<int:pk>/delete/', views.delete_skills, name="delete_skills"),
	#path('skills/<int:pk>/edit/', views.edit_skills, name="edit_skills"),
	#re_path(r'^(.+)/add_item$', views.add_item, name='add_item'),
]